### ISSUE TITLE
Adding restrictions problem

### ISSUE THREAD

**Issue by WaffleMayhem** [dvarnai/store-plugin#18]
Hi I am having a problem with adding restrictions "flags" to some items so that people cannot get the items I want.

>         "VIP"
	    {
		"Name Tags"
		{
			"Owner"
			{
				"flag" "z"
				"tag" "{blue}[Owner]{teamcolor} "
				"price" "100000"
				"type" "nametag"
			}

I do not know the whole "flag levels" or how to format this. I have groups that i would like to add so that only they can purchase the items I wish. I tried using 

>         "VIP"
	    {
		"Name Tags"
		{
			"Owner"
			{
				"flag" "@Owner"
				"tag" "{blue}[Owner]{teamcolor} "
				"price" "100000"
				"type" "nametag"
			}

with no avail. I need help on this please ignore my ignorance because this is my first time messing with code. Thank you.

**Comment by Jose76Tron** [comment]
you cant se a flag @Owner, the owner flag in sourcemod is z

just put

>     "VIP"
    {
    "Name Tags"
    {
        "Owner"
        {
            "flag" "z"
            "tag" "{blue}[Owner]{teamcolor} "
            "price" "100000"
            "type" "nametag"
        }

>

**Comment by WaffleMayhem** [comment]
it still wont do anything. :c
