### ISSUE TITLE
Have these in error logs how to fix?

### ISSUE THREAD

**Issue by nguyenbaodanh** [dvarnai/store-plugin#2]
L 12/31/2015 - 12:16:15: [SM] Native "StartMessage" reported: Client index 0 is invalid
L 12/31/2015 - 12:16:15: [SM] Displaying call stack trace for plugin "store.smx":
L 12/31/2015 - 12:16:15: [SM]   [0]  Line 217, e:\Cloud\Seafile\Business\Store Plugin\addons\sourcemod\scripting\include\usermessages.inc::StartMessageOne()
L 12/31/2015 - 12:16:15: [SM]   [1]  Line 112, e:\Cloud\Seafile\Business\Store Plugin\addons\sourcemod\scripting\include\zephstocks.inc::Chat()
L 12/31/2015 - 12:16:15: [SM]   [2]  Line 87, store/betting.sp::Command_Bet()

**Comment by dvarnai** [comment]
this would only happen if you call the sm_bet function from rcon
