### ISSUE TITLE
Database Connection error

### ISSUE THREAD

**Issue by AticZPrime** [dvarnai/store-plugin#3]
I can't get the Store plugin to work. I don't have the cfg/sourcemod/plugin.store.cfg to change the database settings. Is there another way to change the database connection ? I tried getting help from the allied modder's forum but nobody noticed me :C 

I get this when I open the !admins command : https://gyazo.com/452797bdec2d09676b0f1fdb6ce952c1

"Thirdperson Mode" (1.0) by Zephyrus was successfully loaded
"Store - Trade System" (1.0) by Zephyrus was successfully loaded
 "[ANY] Gifts" (2.3) by Zephyrus was successfully loaded

The store.smx is not showing on my list.
 
L 12/31/2015 - 18:58:24: [store.smx] Database connection is lost or not yet initialized.
L 12/31/2015 - 18:58:24: [store.smx] Database connection is lost or not yet initialized.
L 12/31/2015 - 18:58:24: [SM] Plugin encountered error 25: Call was aborted
L 12/31/2015 - 18:58:24: [SM] Native "SetFailState" reported: Failed to connect to SQL database. Error: [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 12/31/2015 - 18:58:24: [SM] Displaying call stack trace for plugin "store.smx":
L 12/31/2015 - 18:58:24: [SM]   [0]  Line 2110, store.sp::SQLCallback_Connect()

**Comment by dvarnai** [comment]
how did you set up databases.cfg? if you used localhost for hostname, you should change it to 127.0.0.1

**Comment by AticZPrime** [comment]
I tried that, thank you bbe :3
