### ISSUE TITLE
TF2 Things

### ISSUE THREAD

**Issue by Jose76Tron** [dvarnai/store-plugin#4]
The tf2 things for menu dont work like hat dye,or weapon resize, and more things only unusual works

**Comment by dvarnai** [comment]
what do you mean they dont work?

**Comment by Jose76Tron** [comment]
Check this images, theres only unusual effects on the store menu

sorry about my english i speak spanish

![2016-01-05_00001](https://cloud.githubusercontent.com/assets/2407129/12116536/66e728be-b3b2-11e5-9c8d-d940c47703e7.jpg)

![2016-01-05_00002](https://cloud.githubusercontent.com/assets/2407129/12116538/6a56eb06-b3b2-11e5-8ab3-ea3d49571e42.jpg)

Theres only those options on the store menu

**Comment by dvarnai** [comment]
as far as i can see only unusuals and dyes are part of the default items.txt, but dyes are added improperly, i will fix that. you will hve to add the rest yourself, if you do, make sure to  submit a pull request

**Comment by Jose76Tron** [comment]
Okay thanks!

**Comment by Jose76Tron** [comment]
Nice, is fixed!
