### ISSUE TITLE
Trails do not show in menu (CS:GO)

### ISSUE THREAD

**Issue by blackhawk74** [dvarnai/store-plugin#8]
Trails do not display as a menu option.

I am:
Using the latest version of the plugin
On CS:GO
Compiled using the latest compiler
Using the default items.txt
All materials/models/etc are uploaded properly

This wasn't an issue in the original commit.

**Comment by dvarnai** [comment]
i cant confirm this sorry, works just fine, server set up from scratch:

http://pasteboard.co/IbaMZvk.png

**Comment by blackhawk74** [comment]
Recompiled with latest commit, now seems to be working, weird. Changed nothing else on my server, several restarts later, weird. Thanks anyways!
